"""Generate the cricket win-probability JS parity artifacts from sdv-py.

Provenance: sdv-py at PORT_PIN (tools/sdv_py_pin.py), a read-only worktree. Run from
that worktree's project env (the shared guard refuses any other checkout, a dirty one,
or another installed copy; sdv-py files are read from the checkout it imported):

    uv run --project <sdv-py-pin-worktree> python tools/oracle/gen_cricket_wp_oracle.py

Writes
  src/models/data/cricket_wp_tables.json   resource surface + isotonic calibration (exact floats)
  test/fixtures/cricket/espn_ipl_8048_scoreboard.json   verbatim ESPN capture (sdv-py fixture)
  test/fixtures/cricket/espn_ipl_8048_summary_header.json   header subtree of the ESPN summary capture
  test/fixtures/cricket/py_oracle_cricket_wp.json   py match-state + win-prob + expected-runs + wpa outputs
"""
import json, sys, shutil
from pathlib import Path
import polars as pl
from sportsdataverse.cricket.cricket_wpa import cricket_expected_runs, cricket_wpa
from sportsdataverse.cricket.cricket_win_prob import cricket_match_state, cricket_win_probability

js = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(js / "tools"))
from sdv_py_pin import PORT_PIN, pinned_checkout  # noqa: E402

PIN, py = pinned_checkout(PORT_PIN)
fx = py / "tests/fixtures"
models = py / "sportsdataverse/cricket/models"

surf = pl.read_parquet(models / "cricket_resource_surface.parquet")
cal = pl.read_parquet(models / "cricket_winprob_calibration.parquet")
tables = {
    "_provenance": f"sdv-py {PIN} sportsdataverse/cricket/models/*.parquet, converted losslessly",
    "surface": {"columns": ["fmt", "overs_left", "wickets_left", "resource"], "rows": surf.rows()},
    "calibration": {
        f"{f}|{p}": {"x": g.sort("x")["x"].to_list(), "y": g.sort("x")["y"].to_list()}
        # maintain_order: a plain group_by yields the four keys in a random order per run
        for (f, p), g in cal.group_by(["fmt", "phase"], maintain_order=True)
    },
}
(js / "src/models/data/cricket_wp_tables.json").write_text(json.dumps(tables), encoding="utf-8")

out = js / "test/fixtures/cricket"
shutil.copyfile(fx / "espn/cricket/8048/site-v2/scoreboard.json", out / "espn_ipl_8048_scoreboard.json")
summ = json.load(open(fx / "espn/cricket/8048/site-v2/summary.json", encoding="utf-8"))
(out / "espn_ipl_8048_summary_header.json").write_text(json.dumps({"header": summ["header"]}), encoding="utf-8")
sb = json.load(open(fx / "espn/cricket/8048/site-v2/scoreboard.json", encoding="utf-8"))

def rows(df):
    return json.loads(df.write_json())

espn = {}
for name, payload in (("summary", summ), ("scoreboard_event0", sb["events"][0])):
    st = cricket_match_state(payload, fmt="t20")
    espn[name] = {"state": rows(st), "wp": rows(cricket_win_probability(st))}

# Real Cricsheet holdout (male T20I + ODI): deterministic stratified sample.
h = pl.read_parquet(fx / "league_ports/cricket_holdout.parquet").drop("chasing_won")
h = h.with_columns(
    pl.when((pl.col("innings_number") == 2) & pl.col("target").is_not_null()).then(pl.lit("chase")).otherwise(pl.lit("set")).alias("phase"),
    ((pl.col("target").is_not_null()) & (pl.col("runs") >= pl.col("target"))).alias("reached"),
    ((pl.col("target").is_not_null()) & (pl.col("runs") < pl.col("target")) & ((pl.col("wickets") >= 10) | (pl.col("balls_bowled") >= pl.col("balls_total")))).alias("exhausted"),
)
parts = []
for (f, ph), g in h.group_by(["fmt", "phase"], maintain_order=True):
    parts.append(g.gather_every(max(1, g.height // 150)))
parts.append(h.filter(pl.col("reached")).gather_every(max(1, h.filter(pl.col("reached")).height // 25)))
parts.append(h.filter(pl.col("exhausted")).gather_every(max(1, h.filter(pl.col("exhausted")).height // 25)))
parts.append(h.filter(pl.col("wickets") >= 9).gather_every(40))
sample = pl.concat(parts).unique(maintain_order=True)
st = sample.drop("phase", "reached", "exhausted")
wp = cricket_win_probability(st)
hold = {"state": rows(st), "wp": rows(wp)}
# WPA / expected runs: 40 real matches from the WPA holdout (per-over + terminal states), input shuffled
# (seeded) because cricket_wpa sorts by (event_id, innings_number, balls_bowled).
w = pl.read_parquet(fx / "league_ports/cricket_wpa_holdout.parquet").drop("chasing_won", "innings_final_runs")
keep = sorted(w["event_id"].unique().to_list())[::5][:40]
wst = w.filter(pl.col("event_id").is_in(keep)).sample(fraction=1.0, shuffle=True, seed=7)
wwp = cricket_win_probability(wst)
wpa_o = {"state": rows(wst), "wp": rows(wwp), "expected_runs": rows(cricket_expected_runs(wwp)), "wpa": rows(cricket_wpa(wwp))}

(out / "py_oracle_cricket_wp.json").write_text(json.dumps({
    "_provenance": f"sdv-py {PIN}; tests/fixtures/league_ports/cricket_holdout.parquet (real Cricsheet) + espn/cricket/8048 (IPL capture 2026-06-13); generated by tools/oracle/gen_cricket_wp_oracle.py",
    "espn": espn, "holdout": hold, "wpa": wpa_o}), encoding="utf-8")
print("holdout rows", st.height, "tables", surf.height, cal.height)
