// Codegen: render the cross-league ESPN wrapper table + league matrix from the
// vendored endpoint YAML (tools/codegen/endpoints/*.yaml) into TypeScript under
// src/generated/. `--check` fails (exit 1) if the committed output is stale.
//
//   node tools/codegen/generate.mjs           # write
//   node tools/codegen/generate.mjs --check    # drift gate (CI)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { parse } from "yaml";

const here = dirname(fileURLToPath(import.meta.url));
const endpointsDir = join(here, "endpoints");
const generatedDir = join(here, "..", "..", "src", "generated");

const FAMILY_FILES = ["espn_site_v2", "espn_core_v2", "espn_web_v3"];

function loadWrappers() {
  const wrappers = [];
  for (const stem of FAMILY_FILES) {
    const doc = parse(readFileSync(join(endpointsDir, `${stem}.yaml`), "utf8"));
    const fileHost = doc.host;
    for (const ep of doc.endpoints ?? []) {
      wrappers.push({
        short: ep.short,
        family: ep.host ?? fileHost, // per-endpoint host override (e.g. standings)
        scope: ep.scope ?? "universal",
        path: ep.path,
        pathParams: (ep.path_params ?? []).map((p) => p.name),
        queryParams: (ep.extra_params ?? []).map((p) => ({
          name: p.name,
          queryKey: p.query_key,
          ...(p.default !== undefined ? { default: p.default } : {}),
        })),
      });
    }
  }
  return wrappers;
}

function loadLeagues() {
  const doc = parse(readFileSync(join(endpointsDir, "leagues.yaml"), "utf8"));
  return (doc.leagues ?? []).map((l) => ({
    prefix: l.prefix,
    sport: l.sport,
    league: l.league,
    scopes: l.scopes,
    ...(l.league_param ? { leagueParam: true } : {}),
  }));
}

const HEADER =
  "// AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand.\n" +
  "// Run `npm run codegen` to regenerate from tools/codegen/endpoints/*.yaml.\n\n";

function render(importType, name, data) {
  // The const is annotated, so the array's string literals are contextually
  // typed to the Scope / EspnFamily unions — no casts needed.
  return (
    HEADER +
    `import type { ${importType} } from "../core/types.js";\n\n` +
    `export const ${name}: ${importType}[] = ${JSON.stringify(data, null, 2)};\n`
  );
}

const wrappers = loadWrappers();
const leagues = loadLeagues();
const outputs = {
  [join(generatedDir, "wrappers.ts")]: render("WrapperDef", "WRAPPERS", wrappers),
  [join(generatedDir, "leagues.ts")]: render("LeagueConfig", "LEAGUES", leagues),
};

const check = process.argv.includes("--check");
let drift = false;
for (const [file, content] of Object.entries(outputs)) {
  if (check) {
    const current = existsSync(file) ? readFileSync(file, "utf8") : "";
    if (current !== content) {
      console.error(`DRIFT: ${file} is stale — run \`npm run codegen\``);
      drift = true;
    }
  } else {
    mkdirSync(generatedDir, { recursive: true });
    writeFileSync(file, content);
    console.log(`wrote ${file}`);
  }
}

console.log(
  `codegen: ${wrappers.length} wrappers across ${leagues.length} leagues`
);
if (check && drift) process.exit(1);
if (check) console.log("codegen: generated files are up to date");
