// Generated row types of the release loaders (T18b-2), from sdv-py's loader
// schemas (tools/codegen/schemas/loader_schemas.yaml, vendored verbatim: the polars
// dtype of every column of every `load_*` frame, captured from the same release
// parquet the JS loader reads).
//
// Column type rule: the release loader's decode + integer policy (src/core/releases.ts):
//   - an id column (`isIdColumn`, the runtime's own predicate) of integers (`Int*` /
//     `UInt*`) -> `string`; of floats -> `string | number` (an integral DOUBLE becomes
//     the decimal string, a fraction / a DOUBLE past 2^53 stays a number); `String` -> `string`;
//   - other `Int64` / `UInt64` -> `number | bigint` (a BigInt where a value is past
//     2^53, with one SDV_INT64 warning); other integers and floats -> `number`;
//   - `String` -> `string`, `Boolean` -> `boolean`, `Date` / `Datetime(...)` -> `Date`,
//     `List(T)` -> an array of T, `Null` (null in the captured season) -> `unknown`;
//   - every column `| null`, and optional: a season can lack a column another has.
// A row type also has an index signature (`[column: string]: unknown`): a release adds
// columns over the seasons, and a column the schema does not list is still read (as
// `unknown`). test/types/loader-agreement.test.js checks the committed release fixtures
// against these types.
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";
import { isIdColumn } from "./id-columns.mjs";
import { tsKey } from "./row-types.mjs";

const pascal = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

/** The row type name of a loader (`load_nfl_pbp` -> `LoadNflPbpRow`). */
export const loaderRowName = (fn) => `${pascal(fn)}Row`;

/** The TypeScript of one value of polars dtype `dtype` in column `name` (no `| null`). */
function valueType(name, dtype, where) {
  const list = /^List\((.*)\)$/.exec(dtype);
  if (list) return `Array<${valueType(name, list[1], where)} | null>`;
  const id = isIdColumn(name);
  if (/^U?Int(8|16|32|64)$/.test(dtype)) return id ? "string" : /64$/.test(dtype) ? "number | bigint" : "number";
  if (/^Float(32|64)$/.test(dtype)) return id ? "string | number" : "number";
  if (dtype === "String") return "string";
  if (dtype === "Boolean") return "boolean";
  if (dtype === "Date" || dtype.startsWith("Datetime(")) return "Date";
  throw new Error(`loader types: ${where}.${name}: no TypeScript type for polars dtype ${dtype}`);
}

/** The TypeScript of one loader column (see the header). */
export function loaderColumnType(name, dtype, where = "") {
  return dtype === "Null" ? "unknown" : `${valueType(name, dtype, where)} | null`;
}

/** tools/codegen/schemas/loader_schemas.yaml: `load_* -> [{ name, type }]`. */
export function loadLoaderSchemas(schemasDir) {
  const file = join(schemasDir, "loader_schemas.yaml");
  if (!existsSync(file)) throw new Error(`loader types: ${file} is missing (vendored from sdv-py; run npm run vendor)`);
  return parse(readFileSync(file, "utf8"));
}

/**
 * The row interfaces of one league's loaders: `{ source, names, rowOf }` where
 * `rowOf(fn)` is the row type of a loader (a deprecated loader: its replacement's).
 * Every non-deprecated loader must have a schema (a new one fails the codegen).
 */
export function renderLoaderRows(ns, loaders, schemas) {
  const names = [];
  let body =
    "// AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand.\n" +
    "// Run `npm run codegen` to regenerate (tools/codegen/loader-types.mjs).\n" +
    "//\n" +
    `// Row types of the \`sdv.${ns}\` release loaders, from sdv-py's loader schemas\n` +
    "// (tools/codegen/schemas/loader_schemas.yaml). Ids are decimal strings; every column\n" +
    "// is optional and nullable; a column the schema does not list reads as `unknown`.\n";
  const byFn = new Map(loaders.map((ld) => [ld.fn, ld]));
  for (const ld of loaders) {
    if (ld.deprecatedFor) continue;
    const cols = schemas[ld.fn];
    if (!Array.isArray(cols)) throw new Error(`loader types: ${ld.fn} has no loader schema`);
    const name = loaderRowName(ld.fn);
    names.push(name);
    body += `\n/** One row of \`sdv.${ns}.${ld.camel}\` (\`${ld.tag}\`; sdv-py loader schema \`${ld.fn}\`). */\n`;
    body += `export interface ${name} {\n`;
    for (const c of cols) {
      body += `  /** \`${c.type}\`${isIdColumn(c.name) ? " (an id)" : ""} */\n`;
      body += `  ${tsKey(c.name)}?: ${loaderColumnType(c.name, c.type, ld.fn)};\n`;
    }
    body += "  /** A column the loader schema does not list (a release adds columns over the seasons). */\n";
    body += "  [column: string]: unknown;\n}\n";
  }
  const rowOf = (fn) => {
    const ld = byFn.get(fn);
    return ld.deprecatedFor ? loaderRowName(ld.deprecatedFor) : loaderRowName(fn);
  };
  return { source: body, names, rowOf };
}
