// Generated TypeScript parameter types for every wrapper (T18b-2): one named type
// per endpoint, built from the same endpoint YAML that drives the wrappers.
//
// Rule (sdv-py spec.py at the pin, the source of the YAML):
//   - a path param is required unless it says `required: false`, has a `default`
//     or a `default_from`, or is the `now_variant` toggle (absent -> the `/now` path);
//   - an extra (query) param is optional unless it says `required: true`;
//   - YAML `int`, `str` and `int|str` -> `number | string` (both go on the URL as
//     text, and ids come back from parsed rows as decimal strings since v4), `bool` ->
//     `boolean`, `int|List[int]` -> one value or a list of them; no type -> py's `str`;
//   - every param is also accepted under its camelCase alias, as the resolvers
//     look it up (`team_id` or `teamId`), and an optional one may be `null` (unset).
// ESPN params are per endpoint `short` (every league binds the same params; a
// soccer / cricket league adds `league`). Flat families add their per-call
// controls (`headers`, and `api_key` / `token` / ... where FLAT_API_META lists them).
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";

const pascal = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const SCALAR = "number | string";
/** The TypeScript of one YAML param type (see the header). */
export function paramTsType(type = "str", where = "") {
  switch (type) {
    case "int":
    case "str":
    case "int|str":
      return SCALAR;
    case "bool":
      return "boolean";
    case "int|List[int]":
      return `${SCALAR} | ReadonlyArray<${SCALAR}>`;
    default:
      throw new Error(`param types: ${where}: no TypeScript type for YAML param type ${type}`);
  }
}

/** Per-call controls of a flat family that are not query params, by name -> TypeScript. */
export const CONTROL_TYPES = {
  headers: "Record<string, string>",
  api_key: "string",
  strict: "boolean",
  token: "string",
  email: "string",
  password: "string",
  paginate: "boolean",
  max_pages: "number",
};

/**
 * The YAML type and required flag of every param, keyed `<api>.<short>` (ESPN:
 * `espn.<short>`), read straight from the endpoint YAML: the runtime defs carry
 * neither (they are not needed at runtime).
 */
export function loadParamSpecs(endpointsDir, espnFiles, flatFiles) {
  const specs = new Map();
  const add = (key, ep) => {
    const path = new Map((ep.path_params ?? []).map((p) => [p.name, p]));
    const query = new Map((ep.extra_params ?? []).map((p) => [p.name, p]));
    specs.set(key, { path, query });
  };
  for (const stem of espnFiles) {
    const doc = parse(readFileSync(join(endpointsDir, `${stem}.yaml`), "utf8"));
    for (const ep of doc.endpoints ?? []) add(`espn.${ep.short}`, ep);
  }
  for (const stem of flatFiles) {
    const doc = parse(readFileSync(join(endpointsDir, `${stem}.yaml`), "utf8"));
    for (const ep of doc.endpoints ?? []) add(`${doc.api}.${ep.short}`, ep);
  }
  return specs;
}

/**
 * One endpoint's params as TypeScript: `RequiredParam<...> & ... & OptionalParams<{...}>`
 * (or `NoParams`). `def` is the runtime WrapperDef, `spec` its YAML params.
 */
function paramsType(def, spec, where, extraOptional = []) {
  const req = [];
  const opt = [];
  for (const p of def.pathParams ?? []) {
    const y = spec.path.get(p.name);
    const ts = paramTsType(y?.type, `${where}.${p.name}`);
    const optional =
      p.required === false || p.default !== undefined || p.defaultFrom !== undefined || p.name === def.nowToggle;
    (optional ? opt : req).push([p.name, ts]);
  }
  for (const q of def.queryParams ?? []) {
    const y = spec.query.get(q.name);
    const ts = paramTsType(y?.type, `${where}.${q.name}`);
    (y?.required === true && q.default === undefined ? req : opt).push([q.name, ts]);
  }
  opt.push(...extraOptional);
  const seen = new Set();
  for (const [n] of [...req, ...opt]) {
    if (seen.has(n)) throw new Error(`param types: ${where}: param ${n} declared twice`);
    seen.add(n);
  }
  const parts = req.map(([n, t]) => `RequiredParam<${JSON.stringify(n)}, ${t}>`);
  if (opt.length) parts.push(`OptionalParams<{ ${opt.map(([n, t]) => `${n}: ${t}`).join("; ")} }>`);
  return parts.length ? parts.join(" & ") : "NoParams";
}

const HEADER =
  "// AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand.\n" +
  "// Run `npm run codegen` to regenerate (tools/codegen/param-types.mjs).\n" +
  "//\n";

const IMPORT = 'import type { NoParams, OptionalParams, RequiredParam } from "../../core/types.js";\n';

/** The ESPN params type name of an endpoint `short` (shared by every league). */
export const espnParamsName = (short) => `Espn${pascal(short)}Params`;

/**
 * src/generated/params/espn.ts: one params type per ESPN endpoint `short`.
 * Returns `{ source, names }`.
 */
export function renderEspnParams(wrappers, specs) {
  let body =
    HEADER +
    "// The params of every ESPN endpoint, by endpoint `short`: each league's wrapper of it takes\n" +
    "// these (a soccer / cricket league's also `league`). tools/codegen/param-types.mjs has the rule.\n\n" +
    IMPORT;
  const names = [];
  for (const w of wrappers.slice().sort((a, b) => a.short.localeCompare(b.short))) {
    const name = espnParamsName(w.short);
    if (names.includes(name)) throw new Error(`param types: ${name} names two ESPN endpoints`);
    names.push(name);
    const spec = specs.get(`espn.${w.short}`);
    if (!spec) throw new Error(`param types: no YAML params for ESPN ${w.short}`);
    body += `\n/** Params of the ESPN \`${w.short}\` endpoint (\`GET ${w.path}\`), on every league that has it. */\n`;
    body += `export type ${name} = ${paramsType(w, spec, `espn.${w.short}`)};\n`;
  }
  return { source: body, names };
}

/** The params type name of a flat wrapper (from its v4 snake_case name). */
export const flatParamsName = (snake) => `${pascal(snake)}Params`;

/**
 * src/generated/params/<api>.ts: one params type per flat endpoint, plus the family's
 * `<Api>Controls` (per-call controls). `snakeOf(def)` is the wrapper's v4 name.
 * Returns `{ source, names }`.
 */
export function renderFlatParams(api, defs, specs, controls, snakeOf) {
  const ctlName = `${pascal(api)}Controls`;
  const ctl = ["headers", ...Object.keys(controls ?? {}).filter((c) => c !== "headers")].map((c) => {
    if (!CONTROL_TYPES[c]) throw new Error(`param types: ${api}: no TypeScript type for control ${c}`);
    return [c, CONTROL_TYPES[c]];
  });
  let body =
    HEADER +
    `// The params of every \`${api}\` endpoint (path + query params, and the family's per-call\n` +
    "// controls). tools/codegen/param-types.mjs has the rule.\n\n" +
    IMPORT +
    `\n/** Per-call controls of every \`${api}\` wrapper (not sent as query params). */\n` +
    `export type ${ctlName} = OptionalParams<{ ${ctl.map(([n, t]) => `${n}: ${t}`).join("; ")} }>;\n`;
  const names = [ctlName];
  for (const def of defs.slice().sort((a, b) => a.short.localeCompare(b.short))) {
    const snake = snakeOf(def);
    const name = flatParamsName(snake);
    if (names.includes(name)) throw new Error(`param types: ${name} names two ${api} endpoints`);
    names.push(name);
    const spec = specs.get(`${api}.${def.short}`);
    if (!spec) throw new Error(`param types: no YAML params for ${api}.${def.short}`);
    body += `\n/** Params of \`${snake}\` (\`GET ${def.host}${def.path}\`). */\n`;
    body += `export type ${name} = ${paramsType(def, spec, `${api}.${def.short}`)} & ${ctlName};\n`;
  }
  return { source: body, names };
}

/** src/generated/params/index.ts: every params type, re-exported from the package root. */
export function renderParamsBarrel(byModule) {
  let body = HEADER + "// Every generated params type, re-exported from the package root.\n";
  for (const mod of [...byModule.keys()].sort()) {
    body += `\nexport type {\n${byModule.get(mod).map((n) => `  ${n},\n`).join("")}} from "./${mod}.js";\n`;
  }
  return body;
}
