// Release dataset loaders: render the generated `load*` modules + their docs
// from the vendored sdv-py manifest tools/codegen/endpoints/releases.yaml
// (copied verbatim by vendor.mjs — never hand-edit it). Imported by
// generate.mjs, which owns the write / --check loop.
//
//   src/generated/loaders/<league>.ts   one `export const load<Name>` per entry
//                                       (+ snake alias), delegating to
//                                       src/core/releases.ts
//   src/generated/loaders/index.ts      `league -> module` barrel for src/index.ts
//   <league docs dir>/loaders.md        the per-league "Dataset loaders" page
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";

/** sdv-py `spec.SEASON_TOKEN`. */
const SEASON_TOKEN = /\{season(?:\s*\+\s*(\d+))?\}/;

const TS_HEADER =
  "// AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand.\n" +
  "// Run `npm run codegen` to regenerate from tools/codegen/endpoints/releases.yaml\n" +
  "// (vendored verbatim from sportsdataverse-py).\n";

const DOCS_NOTE =
  "{/* AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand. */}\n" +
  "{/* Run `npm run codegen` to regenerate from tools/codegen/endpoints/releases.yaml. */}\n";

const BASE_LABEL = {
  sdv_releases: "sportsdataverse-data releases",
  raw_data: "sportsdataverse raw data",
  nflverse: "nflverse data releases",
};

const toCamel = (s) => s.replace(/_([a-z0-9])/g, (_m, c) => c.toUpperCase());

/** Read releases.yaml into template-ready loader views (manifest order). */
export function loadReleaseLoaders(endpointsDir) {
  const doc = parse(readFileSync(join(endpointsDir, "releases.yaml"), "utf8"));
  const seen = new Set();
  return doc.loaders.map((ld) => {
    const base = doc.bases[ld.base];
    if (!base) throw new Error(`releases.yaml: ${ld.fn} has unknown base "${ld.base}"`);
    const camel = toCamel(ld.fn);
    if (seen.has(camel)) throw new Error(`releases.yaml: duplicate loader name ${camel}`);
    seen.add(camel);
    const token = ld.url.match(SEASON_TOKEN);
    // Release-tag page: GitHub-release assets link their own repo's tag; others
    // (raw.githubusercontent) keep their provenance tag in sportsdataverse-data.
    const tagBase = base.includes("/releases/download/")
      ? base.replace("/releases/download/", "/releases/tag/")
      : "https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/";
    return {
      fn: ld.fn,
      camel,
      league: ld.league,
      url: `${base}${ld.url}`,
      tag: ld.tag,
      tagUrl: `${tagBase}${ld.tag}`,
      baseLabel: BASE_LABEL[ld.base] ?? ld.base,
      minSeason: ld.min_season ?? undefined,
      single: !token,
      seasonOffset: token?.[1] ? Number(token[1]) : 0,
      idInt64: ld.id_int64?.length ? ld.id_int64 : undefined,
      deprecatedFor: ld.deprecated_for ?? undefined,
      notes: ld.notes?.trim() || undefined,
      exampleSeasons: ld.example_args?.seasons ?? 2024,
    };
  });
}

/** Leagues in manifest-first-seen order -> their loaders. */
export function loadersByLeague(loaders) {
  const out = new Map();
  for (const ld of loaders) {
    if (!out.has(ld.league)) out.set(ld.league, []);
    out.get(ld.league).push(ld);
  }
  return out;
}

const jsdocText = (s) => s.replace(/\*\//g, "*\\/");
/** Escape MDX-significant characters in prose. */
const mdxText = (s) => s.replace(/[{}<>]/g, (c) => `\\${c}`);

function exampleCall(ns, ld) {
  return ld.single ? `await sdv.${ns}.${ld.camel}()` : `await sdv.${ns}.${ld.camel}({ seasons: ${ld.exampleSeasons} })`;
}

function seasonNote(ld) {
  const ex = ld.minSeason ?? 1996;
  return (
    `Pass the season's START year (e.g. \`${ex}\` for the ${ex}-${String(ex + 1).slice(-2)} ` +
    `season); the asset is keyed by the END year and the loader translates internally, ` +
    `so a \`season\` column in the rows carries that END year.`
  );
}

function renderLoaderTs(ns, ld) {
  const defConst = ld.fn.toUpperCase();
  const def = { fn: ld.fn, url: ld.url };
  if (ld.minSeason !== undefined) def.minSeason = ld.minSeason;
  if (ld.idInt64) def.idInt64 = ld.idInt64;
  const optsType = ld.single ? "ReleaseLoaderOptions" : "SeasonLoaderOptions";
  let out = "";
  if (!ld.deprecatedFor) out += `\nconst ${defConst}: ReleaseLoaderDef = ${JSON.stringify(def)};\n`;

  const doc = [];
  doc.push(
    ld.deprecatedFor
      ? `Deprecated alias for {@link ${toCamel(ld.deprecatedFor)}} (\`${ld.deprecatedFor}\`), which reads the \`${ld.tag}\` release.`
      : `Load \`${ld.tag}\` (${ld.baseLabel}).`
  );
  doc.push("");
  doc.push(`Source: ${ld.tagUrl}`);
  if (ld.notes) doc.push("", `Note: ${jsdocText(ld.notes)}`);
  if (ld.seasonOffset) doc.push("", seasonNote(ld));
  doc.push("");
  if (ld.single) {
    doc.push(`@param opts - optional \`columns\` / \`timeoutMs\`.`);
  } else {
    const rng = ld.minSeason !== undefined ? ` (>= ${ld.minSeason})` : "";
    doc.push(`@param opts.seasons - a season or a list of seasons${rng}; one with no published asset is skipped with a warning.`);
  }
  doc.push("@param opts.columns - read only these columns (default: all).");
  doc.push("@param opts.timeoutMs - download timeout in ms (default 300000).");
  doc.push(
    "@returns One plain object per row. INT64 columns are numbers when every value is a safe integer, else BigInt (with a warning)." +
      (ld.single ? " An absent asset returns `[]` with a warning." : "")
  );
  if (!ld.single && ld.minSeason !== undefined) {
    doc.push(`@throws SeasonNotFoundError if a season is below ${ld.minSeason}.`);
  }
  doc.push("@throws AssetFetchError if a download fails (never reported as an empty season).");
  if (ld.deprecatedFor) doc.push(`@deprecated Use {@link ${toCamel(ld.deprecatedFor)}}; same \`seasons\` convention.`);
  doc.push(`@example ${exampleCall(ns, ld)};`);
  out += `\n/**\n${doc.map((l) => (l ? ` * ${l}` : " *")).join("\n")}\n */\n`;

  if (ld.deprecatedFor) {
    out +=
      `export const ${ld.camel} = (opts: ${optsType}): Promise<ReleaseRow[]> => {\n` +
      `  warnDeprecatedLoader(${JSON.stringify(ld.fn)}, ${JSON.stringify(ld.deprecatedFor)});\n` +
      `  return ${toCamel(ld.deprecatedFor)}(opts);\n` +
      `};\n`;
  } else if (ld.single) {
    out += `export const ${ld.camel} = (opts: ${optsType} = {}): Promise<ReleaseRow[]> =>\n  loadReleaseAsset(${defConst}, opts);\n`;
  } else {
    out += `export const ${ld.camel} = (opts: ${optsType}): Promise<ReleaseRow[]> =>\n  loadRelease(${defConst}, opts);\n`;
  }
  out += `/** snake_case alias of {@link ${ld.camel}} (py/R parity). */\nexport const ${ld.fn} = ${ld.camel};\n`;
  return out;
}

/** One `src/generated/loaders/<league>.ts` module. */
function renderLeagueModule(ns, loaders) {
  const used = new Set(["ReleaseRow"]);
  const fns = new Set();
  for (const ld of loaders) {
    used.add(ld.single ? "ReleaseLoaderOptions" : "SeasonLoaderOptions");
    if (ld.deprecatedFor) fns.add("warnDeprecatedLoader");
    else {
      used.add("ReleaseLoaderDef");
      fns.add(ld.single ? "loadReleaseAsset" : "loadRelease");
    }
  }
  const imports = [...[...fns].sort(), ...[...used].sort().map((t) => `type ${t}`)];
  let body =
    TS_HEADER +
    "//\n" +
    `// ${loaders.length} dataset loaders for \`sdv.${ns}\`: each reads a published\n` +
    "// SportsDataverse release asset (parquet) through src/core/releases.ts.\n\n" +
    `import {\n${imports.map((i) => `  ${i},`).join("\n")}\n} from "../../core/releases.js";\n`;
  for (const ld of loaders) body += renderLoaderTs(ns, ld);
  return body;
}

function renderBarrel(leagues) {
  const sorted = [...leagues].sort();
  let body =
    TS_HEADER +
    "//\n" +
    "// Barrel for the generated release loaders: `league -> module`, merged onto\n" +
    "// each league namespace by src/index.ts.\n\n";
  for (const lg of sorted) body += `import * as ${toCamel(lg)}Loaders from "./${lg}.js";\n`;
  body += "\nexport const WRITTEN_LOADERS: Record<string, Record<string, unknown>> = {\n";
  for (const lg of sorted) body += `  ${lg}: ${toCamel(lg)}Loaders,\n`;
  body += "};\n";
  return body;
}

/** The per-league "Dataset loaders" reference page. */
export function renderLoadersPage(ns, loaders, position) {
  const bases = [...new Set(loaders.map((l) => l.baseLabel))].join(" / ");
  let body =
    `---\n` +
    `title: Dataset loaders\n` +
    `sidebar_label: Dataset loaders\n` +
    `sidebar_position: ${position}\n` +
    `---\n\n` +
    DOCS_NOTE +
    `\n# \`sdv.${ns}\` — dataset loaders\n\n` +
    `${loaders.length} loader${loaders.length === 1 ? "" : "s"} reading the published ` +
    `${bases} (parquet) — the JS mirror of sportsdataverse-py's \`load_*\` functions. ` +
    `Each is a camelCase export plus its snake_case alias, resolves to an array of plain ` +
    `row objects, and accepts \`columns\` (read only those) and \`timeoutMs\`.\n\n` +
    `- **Seasons:** \`seasons\` takes one season or a list. A season with no published ` +
    `asset (HTTP 404) is skipped with a warning; any other failure raises ` +
    `\`AssetFetchError\` (a failed download is never an empty season); a season below the ` +
    `loader's floor raises \`SeasonNotFoundError\` before anything is fetched. Multi-season ` +
    `results union the columns, null-filling gaps.\n` +
    `- **Integers:** INT64 columns come back as \`number\` when every value is a safe ` +
    `integer, otherwise as \`BigInt\` with one warning naming the column.\n` +
    `- **Runtime:** Node only. Downloads go through the \`releases\` transport family ` +
    `(see [Transport, auth & errors](../../guides/transport-and-auth.md)); each asset is ` +
    `downloaded whole, then decoded.\n\n` +
    `| Loader | Release | Seasons |\n|---|---|---|\n`;
  for (const ld of loaders) {
    const seasons = ld.single ? "one asset" : ld.minSeason !== undefined ? `${ld.minSeason}+` : "—";
    const dep = ld.deprecatedFor ? " *(deprecated)*" : "";
    body += `| [\`${ld.camel}\`](#${ld.camel.toLowerCase()})${dep} | [${ld.tag}](${ld.tagUrl}) | ${seasons} |\n`;
  }
  for (const ld of loaders) {
    body += `\n## \`${ld.camel}\`\n\n`;
    if (ld.deprecatedFor) {
      body += `:::warning[Deprecated]\nUse [\`${toCamel(ld.deprecatedFor)}\`](#${toCamel(ld.deprecatedFor).toLowerCase()}) — same \`seasons\` convention. Emits a one-time \`DeprecationWarning\`.\n:::\n\n`;
    }
    body += `Release: [${ld.tag}](${ld.tagUrl}) · asset \`${ld.url}\`\n\n`;
    if (ld.notes) body += `:::caution[Coverage]\n${mdxText(ld.notes)}\n:::\n\n`;
    if (ld.seasonOffset) body += `${seasonNote(ld)}\n\n`;
    body += `| option | type | required | description |\n|---|---|---|---|\n`;
    if (!ld.single) {
      const rng = ld.minSeason !== undefined ? ` (>= ${ld.minSeason})` : "";
      body += `| \`seasons\` | \`number \\| number[]\` | yes | season(s) to load${rng} |\n`;
    }
    body += `| \`columns\` | \`string[]\` | no | read only these columns |\n`;
    body += `| \`timeoutMs\` | \`number\` | no | download timeout in ms (default 300000) |\n`;
    body += `\n\`\`\`js\nconst rows = ${exampleCall(ns, ld)};\n// snake_case alias (py/R parity): sdv.${ns}.${ld.fn}(...)\n\`\`\`\n`;
  }
  return body;
}

/** "Dataset loaders" section appended to the reference overview (reference/index.md). */
export function renderLoadersIndexSection(byLeague) {
  let body =
    `\n## Dataset loaders\n\n` +
    `\`load*\` functions read the published SportsDataverse release assets (parquet) — ` +
    `play-by-play with EPA/WP, schedules, rosters, box scores, ratings, player value — ` +
    `the way sportsdataverse-py's \`load_*\` functions do. Node only.\n\n` +
    `| Namespace | loaders |\n|---|---:|\n`;
  for (const [ns, loaders] of [...byLeague].sort(([a], [b]) => a.localeCompare(b))) {
    body += `| [${ns}](../${ns}/reference/loaders.md) | ${loaders.length} |\n`;
  }
  return body;
}

/** Landing page for a namespace that has loaders but no ESPN surface (e.g. `pwhl`). */
export function renderLoaderOnlyIndex(ns, loaders, note = "") {
  return (
    `---\n` +
    `title: ${ns.toUpperCase()}\n` +
    `sidebar_label: Overview\n` +
    `sidebar_position: 0\n` +
    `---\n\n` +
    DOCS_NOTE +
    `\n# \`sdv.${ns}\`\n\n` +
    `\`sdv.${ns}\` has no ESPN surface; it carries the ${ns.toUpperCase()} dataset loaders ` +
    `(published SportsDataverse release assets).${note ? ` ${note}` : ""}\n\n` +
    "```js\n" +
    `import sdv from 'sportsdataverse';\n\n` +
    `const rows = ${exampleCall(ns, loaders.find((l) => l.fn.startsWith(`load_${ns}_`)) ?? loaders[0])};\n` +
    "```\n\n" +
    `| Reference | functions |\n|---|---:|\n` +
    `| [Dataset loaders](./reference/loaders.md) | ${loaders.length} |\n`
  );
}

/**
 * Register the generated loader TS modules into `outputs` (path -> content).
 * Docs pages are registered by generate.mjs, which owns the docs layout.
 */
export function registerLoaderModules(outputs, generatedDir, byLeague) {
  const dir = join(generatedDir, "loaders");
  for (const [ns, loaders] of byLeague) {
    outputs[join(dir, `${ns}.ts`)] = renderLeagueModule(ns, loaders);
  }
  outputs[join(dir, "index.ts")] = renderBarrel(byLeague.keys());
}
