// Release dataset loaders: render the generated `load*` modules + their docs
// from the vendored sdv-py manifest tools/codegen/endpoints/releases.yaml
// (copied verbatim by vendor.mjs — never hand-edit it). Imported by
// generate.mjs, which owns the write / --check loop.
//
//   src/generated/loaders/<league>.ts   one `export const load<Name>` per entry
//                                       (+ snake alias), delegating to
//                                       src/core/releases.ts
//   src/generated/loaders/index.ts      `league -> module` barrel for src/index.ts
//   <league docs dir>/loaders.md        the per-league "Dataset loaders" page
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";

/** sdv-py `spec.SEASON_TOKEN`. */
const SEASON_TOKEN = /\{season(?:\s*\+\s*(\d+))?\}/;

const TS_HEADER =
  "// AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand.\n" +
  "// Run `npm run codegen` to regenerate from tools/codegen/endpoints/releases.yaml\n" +
  "// (vendored verbatim from sportsdataverse-py).\n";

const DOCS_NOTE =
  "{/* AUTO-GENERATED by tools/codegen/generate.mjs — do not edit by hand. */}\n" +
  "{/* Run `npm run codegen` to regenerate from tools/codegen/endpoints/releases.yaml. */}\n";

const BASE_LABEL = {
  sdv_releases: "sportsdataverse-data releases",
  raw_data: "sportsdataverse raw data",
  nflverse: "nflverse data releases",
};

const toCamel = (s) => s.replace(/_([a-z0-9])/g, (_m, c) => c.toUpperCase());

/**
 * `columns` for the generated examples of every play-by-play loader and of every
 * loader whose example asset is over the row-format size guard on the default
 * 4 GB heap (45.0M cells) — a full row-object read of those exhausts the heap.
 * Names checked against each example asset's real parquet footer (2026-10-05
 * survey of all 323 example assets); cells = rows × leaf columns of that asset.
 * Every `*pbp*` loader must have an entry; a stale key fails codegen.
 */
const EXAMPLE_COLUMNS = {
  load_cfb_pbp: ["game_id", "period", "text", "EPA", "home_wp_before"], // 82.8M cells (its `id` is > 2^53)
  load_cfb_model_pbp: ["game_id", "period", "text", "epa", "wpa"],
  load_cfb_pbp_r: ["game_id", "play_type", "play_text", "EPA", "wpa"], // 100.3M
  load_mbb_pbp: ["game_id", "sequence_number", "type_text", "text", "score_value"], // 122.3M
  load_wbb_pbp: ["game_id", "sequence_number", "type_text", "text", "score_value"], // 126.0M
  load_nba_pbp: ["game_id", "sequence_number", "type_text", "text", "score_value"], // 41.2M
  load_wnba_pbp: ["game_id", "sequence_number", "type_text", "text", "score_value"],
  load_mlb_pbp: ["game_pk", "inning", "event_type", "description"],
  load_nhl_pbp: ["game_id", "period", "event_type", "description", "strength_state"], // 104.0M
  load_nhl_pbp_full: ["game_id", "period", "event_type", "description", "event"],
  load_nhl_pbp_lite: ["game_id", "period", "event_type", "description", "event"],
  load_nba_stats_pbp: ["game_id", "period", "clock", "event_type", "description"], // 34.7M
  load_nba_stats_pbp_v3: ["game_id", "period", "clock", "event_type", "description"],
  load_wnba_stats_pbp: ["game_id", "period", "clock", "event_type", "description"],
  load_ncaa_baseball_pbp: ["contest_id", "inning", "play_type", "description"],
  load_phf_pbp: ["game_id", "period_id", "play_type", "play_description"],
  load_pwhl_pbp: ["game_id", "period_of_game", "event", "event_type", "strength_state"],
  load_pwhl_xg_pbp: ["game_id", "period_of_game", "sec_from_start", "event_type"],
  load_nfl_pbp: ["game_id", "play_id", "desc", "epa", "wp"],
  load_nfl_model_pbp: ["game_id", "play_id", "desc", "epa", "wp"],
  load_nfl_pbp_participation: ["nflverse_game_id", "play_id", "offense_formation", "defenders_in_box"],
  load_ncaa_mbb_pbp: ["game_date", "home", "away", "period", "event_type", "shot_value"], // 259.4M
  load_ncaa_wbb_pbp: ["game_date", "home", "away", "period", "event_type", "shot_value"], // 249.8M
  load_ncaa_mfb_pbp: ["contest_id", "drive_number", "play_number", "play_type", "play_text"],
  load_ncaa_mfb_pbp_cfbfastr: ["game_id", "id_play", "play_type", "play_text", "yards_gained"],
  load_ncaa_baseball_team_stats: ["contest_id", "category", "stat", "away_value", "home_value"], // 83.8M
  load_ncaa_mbb_possessions: ["game_date", "home", "away", "poss_num", "poss_team"], // 48.8M
  load_ncaa_wbb_possessions: ["game_date", "home", "away", "poss_num", "poss_team"], // 47.1M
};

/** Read releases.yaml into template-ready loader views (manifest order). */
export function loadReleaseLoaders(endpointsDir) {
  const doc = parse(readFileSync(join(endpointsDir, "releases.yaml"), "utf8"));
  const seen = new Set();
  const views = doc.loaders.map((ld) => {
    // Fail closed: sdv-py renders a stub as NotImplementedError; JS has no stub path.
    if (ld.stub) throw new Error(`releases.yaml: ${ld.fn} is a stub; the JS generator has no stub support`);
    if (ld.fn.includes("pbp") && !EXAMPLE_COLUMNS[ld.fn]) {
      throw new Error(`render-loaders: ${ld.fn} needs an EXAMPLE_COLUMNS entry (play-by-play examples pass columns)`);
    }
    const base = doc.bases[ld.base];
    if (!base) throw new Error(`releases.yaml: ${ld.fn} has unknown base "${ld.base}"`);
    const camel = toCamel(ld.fn);
    if (seen.has(camel)) throw new Error(`releases.yaml: duplicate loader name ${camel}`);
    seen.add(camel);
    // sdv-py spec.Loader.on_missing: `skip` (default) | `raise`; anything else fails closed.
    const onMissing = ld.on_missing ?? "skip";
    if (onMissing !== "skip" && onMissing !== "raise") {
      throw new Error(`releases.yaml: ${ld.fn} on_missing must be 'skip' or 'raise', got ${JSON.stringify(ld.on_missing)}`);
    }
    const token = ld.url.match(SEASON_TOKEN);
    // Release-tag page: GitHub-release assets link their own repo's tag; others
    // (raw.githubusercontent) keep their provenance tag in sportsdataverse-data.
    const tagBase = base.includes("/releases/download/")
      ? base.replace("/releases/download/", "/releases/tag/")
      : "https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/";
    return {
      fn: ld.fn,
      camel,
      league: ld.league,
      url: `${base}${ld.url}`,
      tag: ld.tag,
      tagUrl: `${tagBase}${ld.tag}`,
      baseLabel: BASE_LABEL[ld.base] ?? ld.base,
      minSeason: ld.min_season ?? undefined,
      single: !token,
      seasonOffset: token?.[1] ? Number(token[1]) : 0,
      idInt64: ld.id_int64?.length ? ld.id_int64 : undefined,
      raiseOnMissing: onMissing === "raise",
      deprecatedFor: ld.deprecated_for ?? undefined,
      notes: ld.notes?.trim() || undefined,
      exampleSeasons: ld.example_args?.seasons ?? 2024,
      exampleColumns: EXAMPLE_COLUMNS[ld.fn],
    };
  });
  const stale = Object.keys(EXAMPLE_COLUMNS).filter((fn) => !seen.has(toCamel(fn)));
  if (stale.length) throw new Error(`render-loaders: EXAMPLE_COLUMNS names unknown loaders: ${stale.join(", ")}`);
  return views;
}

/** Leagues in manifest-first-seen order -> their loaders. */
export function loadersByLeague(loaders) {
  const out = new Map();
  for (const ld of loaders) {
    if (!out.has(ld.league)) out.set(ld.league, []);
    out.get(ld.league).push(ld);
  }
  return out;
}

const jsdocText = (s) => s.replace(/\*\//g, "*\\/");
/** Escape MDX-significant characters in prose. */
const mdxText = (s) => s.replace(/[{}<>]/g, (c) => `\\${c}`);

function exampleCall(ns, ld) {
  const args = [];
  if (!ld.single) args.push(`seasons: ${ld.exampleSeasons}`);
  if (ld.exampleColumns) args.push(`columns: [${ld.exampleColumns.map((c) => `'${c}'`).join(", ")}]`);
  return `await sdv.${ns}.${ld.camel}(${args.length ? `{ ${args.join(", ")} }` : ""})`;
}

function seasonNote(ld) {
  const ex = ld.minSeason ?? 1996;
  return (
    `Pass the season's START year (e.g. \`${ex}\` for the ${ex}-${String(ex + 1).slice(-2)} ` +
    `season); the asset is keyed by the END year and the loader translates internally, ` +
    `so a \`season\` column in the rows carries that END year.`
  );
}

function renderLoaderTs(ns, ld) {
  const defConst = ld.fn.toUpperCase();
  const def = { fn: ld.fn, url: ld.url };
  if (ld.minSeason !== undefined) def.minSeason = ld.minSeason;
  if (ld.idInt64) def.idInt64 = ld.idInt64;
  if (ld.raiseOnMissing) def.onMissing = "raise";
  const loaderType = ld.single ? "AssetLoader" : "SeasonLoader";
  let out = "";
  if (!ld.deprecatedFor) out += `\nconst ${defConst}: ReleaseLoaderDef = ${JSON.stringify(def)};\n`;

  const doc = [];
  doc.push(
    ld.deprecatedFor
      ? `Deprecated alias for {@link ${toCamel(ld.deprecatedFor)}} (\`${ld.deprecatedFor}\`), which reads the \`${ld.tag}\` release.`
      : `Load \`${ld.tag}\` (${ld.baseLabel}).`
  );
  doc.push("");
  doc.push(`Source: ${ld.tagUrl}`);
  if (ld.notes) doc.push("", `Note: ${jsdocText(ld.notes)}`);
  if (ld.seasonOffset) doc.push("", seasonNote(ld));
  doc.push("");
  if (ld.single) {
    doc.push(`@param opts - optional \`columns\` / \`timeoutMs\`.`);
  } else {
    const rng = ld.minSeason !== undefined ? ` (>= ${ld.minSeason})` : "";
    doc.push(
      `@param opts.seasons - a season or a list of seasons${rng}; one with no published asset ` +
        (ld.raiseOnMissing ? "throws `NoDataError` (sdv-py parity)." : "is skipped with a warning.")
    );
  }
  doc.push("@param opts.columns - read only these columns (default: all).");
  doc.push('@param opts.format - `"rows"` (default) or `"columns"` (`{ [column]: values[] }`, ~4x lighter).');
  doc.push("@param opts.maxCells - size guard (rows × leaf columns); default scales with the heap, `Infinity` disables.");
  doc.push("@param opts.timeoutMs - download timeout in ms (default 300000).");
  doc.push(
    "@returns One plain object per row (or column arrays with `format: \"columns\"`). Id columns (`id`, `*_id`, `*_ids`, `*_pk`, `athlete_id_1`, `id_play`, `playerId`, `start.team.id`, …) of integers are exact decimal strings whatever their stored width (INT32, INT64 or DOUBLE); other INT64 columns are numbers when every value is a safe integer, else BigInt (one warning per column per process)." +
      (ld.single ? " An absent asset returns no rows with a warning." : "")
  );
  if (!ld.single && ld.minSeason !== undefined) {
    doc.push(`@throws SeasonNotFoundError if a season is below ${ld.minSeason}.`);
  }
  if (ld.raiseOnMissing) {
    doc.push(`@throws NoDataError if a requested ${ld.single ? "asset" : "season"} has no published asset (HTTP 404).`);
  }
  doc.push("@throws SdvError if the data is over `maxCells` (checked before decoding).");
  doc.push("@throws AssetFetchError if a download fails (never reported as an empty season).");
  if (ld.deprecatedFor) doc.push(`@deprecated Use {@link ${toCamel(ld.deprecatedFor)}}; same \`seasons\` convention.`);
  doc.push(`@example ${exampleCall(ns, ld)};`);
  out += `\n/**\n${doc.map((l) => (l ? ` * ${l}` : " *")).join("\n")}\n */\n`;

  if (ld.deprecatedFor) {
    out +=
      `export const ${ld.camel} = deprecatedLoader<${loaderType}>(\n` +
      `  ${JSON.stringify(ld.fn)},\n  ${JSON.stringify(ld.deprecatedFor)},\n` +
      `  () => ${toCamel(ld.deprecatedFor)}\n);\n`;
  } else {
    out += `export const ${ld.camel} = ${ld.single ? "assetLoader" : "seasonLoader"}(${defConst});\n`;
  }
  out += `/** snake_case alias of {@link ${ld.camel}} (py/R parity). */\nexport const ${ld.fn} = ${ld.camel};\n`;
  return out;
}

/** One `src/generated/loaders/<league>.ts` module. */
function renderLeagueModule(ns, loaders) {
  const used = new Set();
  const fns = new Set();
  for (const ld of loaders) {
    if (ld.deprecatedFor) {
      fns.add("deprecatedLoader");
      used.add(ld.single ? "AssetLoader" : "SeasonLoader");
    } else {
      used.add("ReleaseLoaderDef");
      fns.add(ld.single ? "assetLoader" : "seasonLoader");
    }
  }
  const imports = [...[...fns].sort(), ...[...used].sort().map((t) => `type ${t}`)];
  let body =
    TS_HEADER +
    "//\n" +
    `// ${loaders.length} dataset loaders for \`sdv.${ns}\`: each reads a published\n` +
    "// SportsDataverse release asset (parquet) through src/core/releases.ts.\n\n" +
    `import {\n${imports.map((i) => `  ${i},`).join("\n")}\n} from "../../core/releases.js";\n`;
  for (const ld of loaders) body += renderLoaderTs(ns, ld);
  return body;
}

function renderBarrel(leagues) {
  const sorted = [...leagues].sort();
  let body =
    TS_HEADER +
    "//\n" +
    "// Barrel for the generated release loaders: `league -> module`, merged onto\n" +
    "// each league namespace by src/index.ts.\n\n";
  for (const lg of sorted) body += `import * as ${toCamel(lg)}Loaders from "./${lg}.js";\n`;
  body += "\nexport const WRITTEN_LOADERS: Record<string, Record<string, unknown>> = {\n";
  for (const lg of sorted) body += `  ${lg}: ${toCamel(lg)}Loaders,\n`;
  body += "};\n";
  return body;
}

/** The per-league "Dataset loaders" reference page. */
export function renderLoadersPage(ns, loaders, position) {
  const bases = [...new Set(loaders.map((l) => l.baseLabel))].join(" / ");
  let body =
    `---\n` +
    `title: Dataset loaders\n` +
    `sidebar_label: Dataset loaders\n` +
    `sidebar_position: ${position}\n` +
    `---\n\n` +
    DOCS_NOTE +
    `\n# \`sdv.${ns}\` — dataset loaders\n\n` +
    `${loaders.length} loader${loaders.length === 1 ? "" : "s"} reading the published ` +
    `${bases} (parquet) — the JS mirror of sportsdataverse-py's \`load_*\` functions. ` +
    `Each is a camelCase export plus its snake_case alias and resolves to an array of plain ` +
    `row objects (or \`{ [column]: values[] }\` with \`format: "columns"\`).\n\n` +
    `- **Size:** row objects cost ~60-100 bytes per cell on the heap, so before decoding each ` +
    `season a loader adds its rows × columns (from the parquet footer) to a running total and ` +
    `checks it against \`maxCells\` — by default ` +
    `heap limit / 100 for rows (≈45M cells on Node's default 4 GB heap) and heap limit / 30 ` +
    `for \`format: "columns"\` — and throws a catchable \`SdvError\` instead of running out of ` +
    `memory. Play-by-play is the usual case: pass \`columns\`, use \`format: "columns"\`, or ` +
    `raise the heap (\`node --max-old-space-size=8192\`).\n` +
    `- **Seasons:** \`seasons\` takes one season or a list. A season with no published ` +
    `asset (HTTP 404) is skipped with a warning (loaders marked so in their \`seasons\` row — ` +
    `sdv-py's hand-written ones — throw \`NoDataError\` instead); any other failure raises ` +
    `\`AssetFetchError\` (a failed download is never an empty season); a season below the ` +
    `loader's floor raises \`SeasonNotFoundError\` before anything is fetched. Multi-season ` +
    `results union the columns, null-filling gaps, and cast a column whose type changed ` +
    `between seasons to the common type (an integer id that became a string → strings, ` +
    `"123" not "123.0"), as sdv-py's \`diagonal_relaxed\` concat does.\n` +
    `- **Integers:** an id column (\`id\`, \`*_id\`, \`*_ids\`, \`*_pk\`, \`athlete_id_1\`, \`id_play\`, ` +
    `\`playerId\`, \`homeTeamId\`, \`start.team.id\`, …) of integers comes back as ` +
    `exact decimal strings in every row and every season, whatever width the release stores it ` +
    `with (INT32, INT64, or a DOUBLE holding integers: \`"401628579101849903"\`, \`"39"\`, never ` +
    `\`"39.0"\`), so ids join across seasons and across releases. Code-like id columns ` +
    `(\`type_id\`, \`status_id\`, …) are strings too. An id column that is not exact integers ` +
    `(a fraction, a DOUBLE past 2^53) is left as read with one warning. Any other INT64 column ` +
    `comes back as \`number\` when every value is a safe integer, otherwise as \`BigInt\` with one ` +
    `warning (code \`SDV_INT64\`) per column per process.\n` +
    `- **Runtime:** Node only. Downloads go through the \`releases\` transport family ` +
    `(see [Transport, auth & errors](../../guides/transport-and-auth.md)); each asset is ` +
    `downloaded whole, then decoded.\n\n` +
    `| Loader | Release | Seasons |\n|---|---|---|\n`;
  for (const ld of loaders) {
    const seasons = ld.single ? "one asset" : ld.minSeason !== undefined ? `${ld.minSeason}+` : "—";
    const dep = ld.deprecatedFor ? " *(deprecated)*" : "";
    body += `| [\`${ld.camel}\`](#${ld.camel.toLowerCase()})${dep} | [${ld.tag}](${ld.tagUrl}) | ${seasons} |\n`;
  }
  for (const ld of loaders) {
    body += `\n## \`${ld.camel}\`\n\n`;
    if (ld.deprecatedFor) {
      body += `:::warning[Deprecated]\nUse [\`${toCamel(ld.deprecatedFor)}\`](#${toCamel(ld.deprecatedFor).toLowerCase()}) — same \`seasons\` convention. Emits a one-time \`DeprecationWarning\`.\n:::\n\n`;
    }
    body += `Release: [${ld.tag}](${ld.tagUrl}) · asset \`${ld.url}\`\n\n`;
    if (ld.notes) body += `:::caution[Coverage]\n${mdxText(ld.notes)}\n:::\n\n`;
    if (ld.seasonOffset) body += `${seasonNote(ld)}\n\n`;
    body += `| option | type | required | description |\n|---|---|---|---|\n`;
    if (!ld.single) {
      const rng = ld.minSeason !== undefined ? ` (>= ${ld.minSeason})` : "";
      const miss = ld.raiseOnMissing ? "; a season with no published asset throws `NoDataError`" : "";
      body += `| \`seasons\` | \`number \\| number[]\` | yes | season(s) to load${rng}${miss} |\n`;
    }
    body += `| \`columns\` | \`string[]\` | no | read only these columns |\n`;
    body += `| \`format\` | \`"rows" \\| "columns"\` | no | row objects (default) or column arrays |\n`;
    body += `| \`maxCells\` | \`number\` | no | size guard; default scales with the heap, \`Infinity\` disables |\n`;
    body += `| \`timeoutMs\` | \`number\` | no | download timeout in ms (default 300000) |\n`;
    body += `\n\`\`\`js\nconst rows = ${exampleCall(ns, ld)};\n// snake_case alias (py/R parity): sdv.${ns}.${ld.fn}(...)\n\`\`\`\n`;
  }
  return body;
}

/** "Dataset loaders" section appended to the reference overview (reference/index.md). */
export function renderLoadersIndexSection(byLeague) {
  let body =
    `\n## Dataset loaders\n\n` +
    `\`load*\` functions read the published SportsDataverse release assets (parquet) — ` +
    `play-by-play with EPA/WP, schedules, rosters, box scores, ratings, player value — ` +
    `the way sportsdataverse-py's \`load_*\` functions do. Node only.\n\n` +
    `| Namespace | loaders |\n|---|---:|\n`;
  for (const [ns, loaders] of [...byLeague].sort(([a], [b]) => a.localeCompare(b))) {
    body += `| [${ns}](../${ns}/reference/loaders.md) | ${loaders.length} |\n`;
  }
  return body;
}

/** Landing page for a namespace that has loaders but no ESPN surface (e.g. `pwhl`). */
export function renderLoaderOnlyIndex(ns, loaders, note = "") {
  return (
    `---\n` +
    `title: ${ns.toUpperCase()}\n` +
    `sidebar_label: Overview\n` +
    `sidebar_position: 0\n` +
    `---\n\n` +
    DOCS_NOTE +
    `\n# \`sdv.${ns}\`\n\n` +
    `\`sdv.${ns}\` has no ESPN surface; it carries the ${ns.toUpperCase()} dataset loaders ` +
    `(published SportsDataverse release assets).${note ? ` ${note}` : ""}\n\n` +
    "```js\n" +
    `import sdv from 'sportsdataverse';\n\n` +
    `const rows = ${exampleCall(ns, loaders.find((l) => l.fn.startsWith(`load_${ns}_`)) ?? loaders[0])};\n` +
    "```\n\n" +
    `| Reference | functions |\n|---|---:|\n` +
    `| [Dataset loaders](./reference/loaders.md) | ${loaders.length} |\n`
  );
}

/**
 * Register the generated loader TS modules into `outputs` (path -> content).
 * Docs pages are registered by generate.mjs, which owns the docs layout.
 */
export function registerLoaderModules(outputs, generatedDir, byLeague) {
  const dir = join(generatedDir, "loaders");
  for (const [ns, loaders] of byLeague) {
    outputs[join(dir, `${ns}.ts`)] = renderLeagueModule(ns, loaders);
  }
  outputs[join(dir, "index.ts")] = renderBarrel(byLeague.keys());
}
